# Generated by Django 3.1.6 on 2021-05-09 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check',
            old_name='dayornight',
            new_name='Day_or_Night',
        ),
    ]
