# Generated by Django 3.1.6 on 2021-05-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210509_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
