# Generated by Django 3.1.6 on 2021-07-12 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210712_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='Day_or_Night',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], max_length=100),
        ),
        migrations.AlterField(
            model_name='check',
            name='Day_or_Night',
            field=models.CharField(choices=[('Day', 'Day'), ('Night', 'Night')], max_length=100),
        ),
    ]
