# Generated by Django 3.1.4 on 2021-08-02 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20210712_0909'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=300)),
                ('picture', models.CharField(default='', max_length=10000)),
                ('short_description', models.CharField(blank=True, default='', max_length=2000)),
                ('complete_description', models.CharField(blank=True, default='', max_length=2000)),
                ('tower_height', models.CharField(blank=True, default='', max_length=200)),
                ('frequency', models.CharField(blank=True, default='', max_length=200)),
                ('resistance', models.CharField(blank=True, default='', max_length=200)),
                ('skin_depth', models.CharField(blank=True, default='', max_length=200)),
                ('temperature_effect', models.CharField(blank=True, default='', max_length=200)),
                ('spacing_between_bundled_conductors', models.CharField(blank=True, default='', max_length=200)),
                ('spacing_between_conductors', models.CharField(blank=True, default='', max_length=200)),
                ('current_carrying_capacity', models.CharField(blank=True, default='', max_length=200)),
                ('inductance_of_transmission_lines', models.CharField(blank=True, default='', max_length=200)),
                ('capacitance', models.CharField(blank=True, default='', max_length=200)),
                ('capacitive_reactance', models.CharField(blank=True, default='', max_length=200)),
                ('conductor_type', models.CharField(blank=True, choices=[('Aluminum Conductor Steel Reinforced (ACSR)', 'Aluminum Conductor Steel Reinforced (ACSR)'), ('All Aluminium conductors (AAC)', 'All Aluminium conductors (AAC)'), ('Aluminium conductor, Alloy-Reinforced (ACAR)', 'Aluminium conductor, Alloy-Reinforced (ACAR)')], default='', max_length=200)),
                ('conductor_length', models.CharField(blank=True, default='', max_length=200)),
                ('conductor_crosssectional_area', models.CharField(blank=True, default='', max_length=200)),
                ('span', models.CharField(blank=True, default='', max_length=200)),
                ('commulative_line_loading', models.CharField(blank=True, default='', max_length=200)),
                ('cable_configuration', models.CharField(blank=True, choices=[('horizontal', 'horizontal'), ('vertical', 'vertical')], default='', max_length=200)),
                ('power_transmitted_in_MVA', models.CharField(blank=True, default='', max_length=200)),
                ('power_received_at_load_in_MVA', models.CharField(blank=True, default='', max_length=200)),
                ('efficiency', models.CharField(blank=True, default='', max_length=200)),
                ('sending_end_voltage_in_KV', models.CharField(blank=True, default='', max_length=200)),
                ('receiving_end_voltage_in_KV', models.CharField(blank=True, default='', max_length=200)),
                ('voltage_regulation', models.CharField(blank=True, default='', max_length=200)),
                ('corona_losses', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='Check',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
