# Generated by Django 3.1.4 on 2021-08-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20210802_1014'),
    ]

    operations = [
        migrations.AddField(
            model_name='tower',
            name='line_type',
            field=models.CharField(blank=True, choices=[('SINGLE CIRCUIT UNBUNDLED', 'SINGLE CIRCUIT UNBUNDLED'), ('DOUBLE CIRCUIT UNBUNDLED', 'DOUBLE CIRCUIT UNBUNDLED'), ('DOUBLE CIRCUIT BUNDLED (3C)', 'DOUBLE CIRCUIT BUNDLED (3C)'), ('DOUBLE CIRCUIT BUNDLED (4C)', 'DOUBLE CIRCUIT BUNDLED (4C)')], default='', max_length=200),
        ),
    ]
